In [89]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [90]:
!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

Reading package lists... Done
Building dependency tree       
Reading state information... Done
fonts-nanum is already the newest version (20180306-3).
The following package was automatically installed and is no longer required:
  libnvidia-common-510
Use 'sudo apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 21 not upgraded.
/usr/share/fonts: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/truetype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/truetype/humor-sans: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 10 fonts, 0 dirs
/usr/local/share/fonts: caching, new cache contents: 0 fonts, 0 dirs
/root/.local/share/fonts: skipping, no such directory
/root/.fonts: skipping, no such directory
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/truetype/humor-san

In [91]:
import pandas as pd
import matplotlib.gridspec as gridspec
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler

plt.rc('font', family='NanumBarunGothic') 

# 각파일read

In [92]:
health = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/국민건강영양조사데이터경진대회/nationalhealth_2010to2021.csv')

In [93]:
health['age'] = health['age'].astype('int')
health

ID       ID_fam    year  region  town_t  sex  age  incm  \
0      b'A308780901'  b'A3087809'  2010.0     1.0     1.0  1.0   74   3.0   
1      b'A309099802'  b'A3090998'  2010.0     1.0     1.0  2.0   71   2.0   
2      b'A309460901'  b'A3094609'  2010.0     1.0     1.0  2.0   61   3.0   
3      b'A309460902'  b'A3094609'  2010.0     1.0     1.0  1.0   32   2.0   
4      b'A310439801'  b'A3104398'  2010.0     1.0     1.0  2.0   63   4.0   
...              ...          ...     ...     ...     ...  ...  ...   ...   
35624  b'R904322404'  b'R9043224'  2021.0     8.0     2.0  1.0   53   3.0   
35625  b'R904332601'  b'R9043326'  2021.0     8.0     2.0  1.0   50   2.0   
35626  b'R904346201'  b'R9043462'  2021.0     8.0     2.0  2.0   54   4.0   
35627  b'R904353001'  b'R9043530'  2021.0     8.0     2.0  1.0   45   3.0   
35628  b'R904353002'  b'R9043530'  2021.0     8.0     2.0  2.0   43   3.0   

       ho_incm  incm5  ...  고콜레스테롤혈증  고중성지방혈증  B형간염   빈혈  뇌졸중  협심증또는심근경색증  \
0          2.0    4.0  ...       0.0      1.0   0.0  0.0 -1.0        -1.0   
1          1.0    2.0  ...       0.0      0.0   0.0  0.0 -1.0        -1.0   
2          2.0    4.0  ...       0.0      0.0   0.0  0.0 -1.0        -1.0   
3          2.0    2.0  ...       0.0      1.0   0.0  0.0 -1.0        -1.0   
4          4.0    5.0  ...       0.0      0.0   0.0  0.0 -1.0        -1.0   
...        ...    ...  ...       ...      ...   ...  ...  ...         ...   
35624      3.0    3.0  ...       0.0      0.0   0.0  0.0  0.0         0.0   
35625      2.0    2.0  ...       0.0      1.0   0.0  0.0  0.0         0.0   
35626      4.0    4.0  ...       0.0      0.0   0.0  0.0  0.0         0.0   
35627      3.0    3.0  ...       0.0      1.0   0.0  0.0  0.0         0.0   
35628      3.0    3.0  ...       0.0      0.0   0.0  0.0  0.0         0.0   

        천식  아토피피부염  골관절염  우울증  
0      0.0    -1.0  -1.0 -1.0  
1     -1.0    -1.0  -1.0 -1.0  
2      1.0    -1.0   1.0 -1.0  
3     -1.0    -1.0  -1.0  1.0  
4     -1.0    -1.0   1.0 -1.0  
...    ...     ...   ...  ...  
35624  0.0     0.0   0.0  0.0  
35625  0.0     0.0   0.0  0.0  
35626  0.0     0.0   0.0  0.0  
35627  0.0     0.0   0.0  0.0  
35628  0.0     0.0   0.0  0.0  

[35629 rows x 122 columns]

In [94]:
health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35629 entries, 0 to 35628
Columns: 122 entries, ID to 우울증
dtypes: float64(119), int64(1), object(2)
memory usage: 33.2+ MB


In [95]:
print(health.columns.tolist())

['ID', 'ID_fam', 'year', 'region', 'town_t', 'sex', 'age', 'incm', 'ho_incm', 'incm5', 'ho_incm5', 'edu', 'occp', 'cfam', 'genertn', 'allownc', 'marri_1', 'marri_2', 'fam_rela', 'tins', 'D_1_1', 'educ', 'EC1_1', 'EC_wht_23', 'EC_wht_5', 'EC_pedu_1', 'EC_pedu_2', 'BD1_11', 'BD2_1', 'BD2_31', 'dr_month', 'BP6_10', 'BP7', 'mh_stress', 'BS3_1', 'BE3_31', 'BE5_1', 'LW_mt', 'LW_mt_a1', 'LW_br', 'HE_fst', 'HE_HPdr', 'HE_DMdr', 'HE_mens', 'HE_prg', 'HE_HPfh1', 'HE_HPfh2', 'HE_HPfh3', 'HE_HLfh1', 'HE_HLfh2', 'HE_HLfh3', 'HE_IHDfh1', 'HE_IHDfh2', 'HE_IHDfh3', 'HE_STRfh1', 'HE_STRfh2', 'HE_STRfh3', 'HE_DMfh1', 'HE_DMfh2', 'HE_DMfh3', 'HE_rPLS', 'HE_sbp', 'HE_dbp', 'HE_ht', 'HE_wt', 'HE_wc', 'HE_BMI', 'HE_glu', 'HE_HbA1c', 'HE_chol', 'HE_HDL_st2', 'HE_TG', 'HE_ast', 'HE_alt', 'HE_hepaB', 'HE_HB', 'HE_HCT', 'HE_BUN', 'HE_crea', 'HE_WBC', 'HE_RBC', 'HE_Bplt', 'HE_Uph', 'HE_Unitr', 'HE_Usg', 'HE_Upro', 'HE_Uglu', 'HE_Uket', 'HE_Ubil', 'HE_Ubld', 'HE_Uro', 'HE_Ucrea', 'N_INTK', 'N_EN', 'N_WATER', 'N_P

In [96]:
health_info = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/국민건강영양조사데이터경진대회/modified_meta_data20.xlsx',engine='openpyxl')

In [97]:
pd.set_option('display.max_rows', None) ## 모든 열을 출력한다.
pd.set_option('display.max_columns', None) ## 모든 열을 출력한다.


health_info



Unnamed: 0    variable    variable description  \
0             0          ID                  개인 아이디   
1             1      ID_fam                  가구 아이디   
2             2        year                    조사연도   
3             3      region                  17개 시도   
4             4      town_t                 동/읍면 구분   
5             5         sex                      성별   
6             6         age                     만나이   
7             7        incm             소득 4분위수(개인)   
8             8     ho_incm             소득 4분위수(가구)   
9             9       incm5             소득 5분위수(개인)   
10           10    ho_incm5             소득 5분위수(가구)   
11           11         edu             교육수준 재분류 코드   
12           12        occp  직업재분류 및 실업/비경제활동 상태 코드   
13           13        cfam                    가구원수   
14           14     genertn               가구 세대구성코드   
15           15     allownc               기초생활수급 여부   
16           16     marri_1                    결혼여부   
17           17     marri_2                    결혼상태   
18           18    fam_rela                가구주와의 관계   
19           19        tins                  건강보험종류   
20           20       D_1_1                주관적 건강인지   
21           21        educ                교육수준: 학력   
22           22       EC1_1                 경제활동 상태   
23           23   EC_wht_23              주당 평균 근로시간   
24           24    EC_wht_5                  변형근로시간   
25           25   EC_pedu_1    (성인) 유년기환경: 아버지 교육수준   
26           26   EC_pedu_2    (성인) 유년기환경: 어머니 교육수준   
27           27      BD1_11       (만12세이상) 1년간 음주빈도   
28           28       BD2_1   (만12세이상) 한 번에 마시는 음주량   
29           29      BD2_31          (만12세이상) 폭음 빈도   
30           30    dr_month                   월간음주율   
31           31      BP6_10            1년간 자살 생각 여부   
32           32         BP7             1년간 정신문제 상담   
33           33   mh_stress                스트레스 인지율   
34           34       BS3_1  (성인) 현재 일반담배(궐련) 흡연 여부   
35           35      BE3_31              1주일간 걷기 일수   
36           36       BE5_1            1주일간 근력운동 일수   
37           37       LW_mt           (만15세이상) 출산경험   
38           38    LW_mt_a1         (만15세이상) 첫 출산연령   
39           39       LW_br              모유수유 경험 여부   
40           40      HE_fst                    공복시간   
41           41     HE_HPdr        검진당일 고혈압 약 복용 여부   
42           42     HE_DMdr        검진당일 당뇨병 약 복용 여부   
43           43     HE_mens                    생리여부   
44           44      HE_prg                    임신여부   
45           45    HE_HPfh1          고혈압 의사진단 여부(부)   
46           46    HE_HPfh2          고혈압 의사진단 여부(모)   
47           47    HE_HPfh3       고혈압 의사진단 여부(형제자매)   
48           48    HE_HLfh1         고지혈증 의사진단 여부(부)   
49           49    HE_HLfh2         고지혈증 의사진단 여부(모)   
50           50    HE_HLfh3      고지혈증 의사진단 여부(형제자매)   
51           51   HE_IHDfh1      허혈성심장질환 의사진단 여부(부)   
52           52   HE_IHDfh2      허혈성심장질환 의사진단 여부(모)   
53           53   HE_IHDfh3   허혈성심장질환 의사진단 여부(형제자매)   
54           54   HE_STRfh1          뇌졸중 의사진단 여부(부)   
55           55   HE_STRfh2          뇌졸중 의사진단 여부(모)   
56           56   HE_STRfh3       뇌졸중 의사진단 여부(형제자매)   
57           57    HE_DMfh1          당뇨병 의사진단 여부(부)   
58           58    HE_DMfh2          당뇨병 의사진단 여부(모)   
59           59    HE_DMfh3       당뇨병 의사진단 여부(형제자매)   
60           60     HE_rPLS               맥박 규칙성 여부   
61           61      HE_sbp      최종 수축기 혈압(2,3차 평균)   
62           62      HE_dbp      최종 이완기 혈압(2,3차 평균)   
63           63       HE_ht                      신장   
64           64       HE_wt                      체중   
65           65       HE_wc                    허리둘레   
66           66      HE_BMI                   체질량지수   
67           67      HE_glu                    공복혈당   
68           68    HE_HbA1c                   당화혈색소   
69           69     HE_chol                  총콜레스테롤   
70           70  HE_HDL_st2          HDL-콜레스테롤(보정값)   
71           71       HE_TG                  

In [98]:
pd.options.display.max_rows = 60
pd.options.display.max_columns = 20


In [99]:
health_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 109 entries, 0 to 108
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Unnamed: 0            109 non-null    int64  
 1   variable              109 non-null    object 
 2   variable description  109 non-null    object 
 3   option description    65 non-null     object 
 4   etc                   109 non-null    object 
 5   data type             109 non-null    object 
 6   not applicable        27 non-null     float64
 7   unknown               40 non-null     object 
 8   variable bins         44 non-null     object 
 9   selected              109 non-null    int64  
dtypes: float64(1), int64(2), object(7)
memory usage: 8.6+ KB


## 여기까지데이터보기 끝

#csv 전처리

##독거노인 일반사람 not독거노인 csv만들기

전체독거노인

In [100]:
def dsiease_count(x):
  cnt=0
  for i in disease:
    if x[i] == 1:
      cnt+=1

  return cnt

health['총질병수'] = health.apply(dsiease_count, axis=1) ##총질병수전처리

alone_old_grand = health.query("cfam==1 and fam_rela==1 and age>=65") #65세이상 독거노인
not_alone_old_grand = health.query("cfam!=1 or fam_rela!=1 and age>=65")# 65세이상 독거노인이아닌사람 
young_person = health.query("age<65")

In [101]:
not_alone_old_grand

ID       ID_fam    year  region  town_t  sex  age  incm  \
0      b'A308780901'  b'A3087809'  2010.0     1.0     1.0  1.0   74   3.0   
1      b'A309099802'  b'A3090998'  2010.0     1.0     1.0  2.0   71   2.0   
2      b'A309460901'  b'A3094609'  2010.0     1.0     1.0  2.0   61   3.0   
3      b'A309460902'  b'A3094609'  2010.0     1.0     1.0  1.0   32   2.0   
5      b'A310980901'  b'A3109809'  2010.0     1.0     1.0  1.0   80   1.0   
...              ...          ...     ...     ...     ...  ...  ...   ...   
35624  b'R904322404'  b'R9043224'  2021.0     8.0     2.0  1.0   53   3.0   
35625  b'R904332601'  b'R9043326'  2021.0     8.0     2.0  1.0   50   2.0   
35626  b'R904346201'  b'R9043462'  2021.0     8.0     2.0  2.0   54   4.0   
35627  b'R904353001'  b'R9043530'  2021.0     8.0     2.0  1.0   45   3.0   
35628  b'R904353002'  b'R9043530'  2021.0     8.0     2.0  2.0   43   3.0   

       ho_incm  incm5  ...  고중성지방혈증  B형간염   빈혈  뇌졸중  협심증또는심근경색증   천식  아토피피부염  \
0          2.0    4.0  ...      1.0   0.0  0.0 -1.0        -1.0  0.0    -1.0   
1          1.0    2.0  ...      0.0   0.0  0.0 -1.0        -1.0 -1.0    -1.0   
2          2.0    4.0  ...      0.0   0.0  0.0 -1.0        -1.0  1.0    -1.0   
3          2.0    2.0  ...      1.0   0.0  0.0 -1.0        -1.0 -1.0    -1.0   
5          1.0    2.0  ...      0.0   0.0  0.0 -1.0        -1.0 -1.0    -1.0   
...        ...    ...  ...      ...   ...  ...  ...         ...  ...     ...   
35624      3.0    3.0  ...      0.0   0.0  0.0  0.0         0.0  0.0     0.0   
35625      2.0    2.0  ...      1.0   0.0  0.0  0.0         0.0  0.0     0.0   
35626      4.0    4.0  ...      0.0   0.0  0.0  0.0         0.0  0.0     0.0   
35627      3.0    3.0  ...      1.0   0.0  0.0  0.0         0.0  0.0     0.0   
35628      3.0    3.0  ...      0.0   0.0  0.0  0.0         0.0  0.0     0.0   

       골관절염  우울증  총질병수  
0      -1.0 -1.0     3  
1      -1.0 -1.0     2  
2       1.0 -1.0     5  
3      -1.0  1.0     4  
5       1.0 -1.0     2  
...     ...  ...   ...  
35624   0.0  0.0     2  
35625   0.0  0.0     1  
35626   0.0  0.0     0  
35627   0.0  0.0     3  
35628   0.0  0.0     0  

[31340 rows x 123 columns]

In [102]:
# alone_old_grand.to_csv('전체독거노인.csv')

In [103]:
seoul_alone_old_grand = alone_old_grand.query("region==1")
busan_alone_old_grand = alone_old_grand.query("region==2")
daegu_alone_old_grand = alone_old_grand.query("region==3")
incheon_alone_old_grand = alone_old_grand.query("region==4")
gwangju_alone_old_grand = alone_old_grand.query("region==5")
daejeon_alone_old_grand = alone_old_grand.query("region==6")
ulsan_alone_old_grand = alone_old_grand.query("region==7")
sejong_alone_old_grand = alone_old_grand.query("region==8")
gyeonggi_alone_old_grand = alone_old_grand.query("region==9")
gangwon_alone_old_grand = alone_old_grand.query("region==10")
chungbuk_alone_old_grand = alone_old_grand.query("region==11")
chungnam_alone_old_grand = alone_old_grand.query("region==12")
jeonbuk_alone_old_grand = alone_old_grand.query("region==13")
jeonnam_alone_old_grand = alone_old_grand.query("region==14")
gyeongbuk_alone_old_grand = alone_old_grand.query("region==15")
gyeongnam_alone_old_grand = alone_old_grand.query("region==16")
jeju_alone_old_grand = alone_old_grand.query("region==17")

#지역별 독거노인들

In [104]:
# seoul_alone_old_grand.

# result1 = pd.concat([seoul_alone_old_grand,busan_alone_old_grand,daegu_alone_old_grand,incheon_alone_old_grand,gwangju_alone_old_grand,daejeon_alone_old_grand,
#                      ulsan_alone_old_grand,sejong_alone_old_grand,gyeonggi_alone_old_grand,gangwon_alone_old_grand,chungbuk_alone_old_grand,
#                      chungnam_alone_old_grand,jeonbuk_alone_old_grand,jeonnam_alone_old_grand,gyeongbuk_alone_old_grand,gyeongnam_alone_old_grand
#                      ,jeju_alone_old_grand],axis=0)

In [105]:
# result1.to_csv('지역별 독거노인들.csv')

In [106]:
seoul_not_alone_old_grand = not_alone_old_grand.query("region==1")
busan_not_alone_old_grand = not_alone_old_grand.query("region==2")
daegu_not_alone_old_grand = not_alone_old_grand.query("region==3")
incheon_not_alone_old_grand = not_alone_old_grand.query("region==4")
gwangju_not_alone_old_grand = not_alone_old_grand.query("region==5")
daejeon_not_alone_old_grand = not_alone_old_grand.query("region==6")
ulsan_not_alone_old_grand = not_alone_old_grand.query("region==7")
sejong_not_alone_old_grand = not_alone_old_grand.query("region==8")
gyeonggi_not_alone_old_grand = not_alone_old_grand.query("region==9")
gangwon_not_alone_old_grand = not_alone_old_grand.query("region==10")
chungbuk_not_alone_old_grand = not_alone_old_grand.query("region==11")
chungnam_not_alone_old_grand = not_alone_old_grand.query("region==12")
jeonbuk_not_alone_old_grand = not_alone_old_grand.query("region==13")
jeonnam_not_alone_old_grand = not_alone_old_grand.query("region==14")
gyeongbuk_not_alone_old_grand = not_alone_old_grand.query("region==15")
gyeongnam_not_alone_old_grand = not_alone_old_grand.query("region==16")
jeju_not_alone_old_grand = not_alone_old_grand.query("region==17")

#지역별 독거아닌 노인들

In [107]:
result2 = pd.concat([seoul_not_alone_old_grand,busan_not_alone_old_grand,daegu_not_alone_old_grand,incheon_not_alone_old_grand,gwangju_not_alone_old_grand,
                     daejeon_not_alone_old_grand,
                     ulsan_not_alone_old_grand,sejong_not_alone_old_grand,gyeonggi_not_alone_old_grand,gangwon_not_alone_old_grand,chungbuk_not_alone_old_grand,
                     chungnam_not_alone_old_grand,jeonbuk_not_alone_old_grand,jeonnam_not_alone_old_grand,gyeongbuk_not_alone_old_grand,gyeongnam_not_alone_old_grand
                     ,jeju_not_alone_old_grand],axis=0)

In [108]:
# result2.to_csv('지역별 독거노인이 아닌사람들.csv')

## csv와 관련된 엑셀파일 전처리

In [109]:
# 개인아이디 가구아이디 조사연도 17개시도 동/읍면구분 성별 나이 소득분위 교육수준 

# incm과 관련된문항 소득분위

# HE와 관련된문항  #건강검진부분
#N과관련된 문항 #1일 영양소섭취와 관련된문항
#EC와 경제수준과 관련된문항
#BD부분 음주와 흡연
#BP부분 정신적 우울감관련
#BE부분 운동여부관련
#LW는 출산여부관련
# BS3_1 #흡연관련
# mh_stress #스트레스인지율

In [110]:
health.columns.tolist()

['ID',
 'ID_fam',
 'year',
 'region',
 'town_t',
 'sex',
 'age',
 'incm',
 'ho_incm',
 'incm5',
 'ho_incm5',
 'edu',
 'occp',
 'cfam',
 'genertn',
 'allownc',
 'marri_1',
 'marri_2',
 'fam_rela',
 'tins',
 'D_1_1',
 'educ',
 'EC1_1',
 'EC_wht_23',
 'EC_wht_5',
 'EC_pedu_1',
 'EC_pedu_2',
 'BD1_11',
 'BD2_1',
 'BD2_31',
 'dr_month',
 'BP6_10',
 'BP7',
 'mh_stress',
 'BS3_1',
 'BE3_31',
 'BE5_1',
 'LW_mt',
 'LW_mt_a1',
 'LW_br',
 'HE_fst',
 'HE_HPdr',
 'HE_DMdr',
 'HE_mens',
 'HE_prg',
 'HE_HPfh1',
 'HE_HPfh2',
 'HE_HPfh3',
 'HE_HLfh1',
 'HE_HLfh2',
 'HE_HLfh3',
 'HE_IHDfh1',
 'HE_IHDfh2',
 'HE_IHDfh3',
 'HE_STRfh1',
 'HE_STRfh2',
 'HE_STRfh3',
 'HE_DMfh1',
 'HE_DMfh2',
 'HE_DMfh3',
 'HE_rPLS',
 'HE_sbp',
 'HE_dbp',
 'HE_ht',
 'HE_wt',
 'HE_wc',
 'HE_BMI',
 'HE_glu',
 'HE_HbA1c',
 'HE_chol',
 'HE_HDL_st2',
 'HE_TG',
 'HE_ast',
 'HE_alt',
 'HE_hepaB',
 'HE_HB',
 'HE_HCT',
 'HE_BUN',
 'HE_crea',
 'HE_WBC',
 'HE_RBC',
 'HE_Bplt',
 'HE_Uph',
 'HE_Unitr',
 'HE_Usg',
 'HE_Upro',
 'HE_Uglu',
 '

In [111]:
nutritionF = ['N_INTK','N_EN','N_WATER','N_PROT','N_FAT','N_CHO','N_CA','N_PHOS','N_FE','N_NA','N_K','N_CAROT','N_RETIN','N_B1','N_B2','N_NIAC','N_VITC']
nutritionF_name = [
  '식품섭취량',
 '에너지',
 '수분',
 '단백질',
 '지방',
 '탄수화물',
 '칼슘',
 '인',
 '철',
 '나트륨',
 '칼륨',
 '베타카로틴',
 '레티놀',
 '티아민',
 '리보플라빈',
 '나이아신',
 '비타민C']

disease = ['비만','고혈압','당뇨병','고콜레스테롤혈증','고중성지방혈증','B형간염','빈혈','뇌졸중','협심증또는심근경색증','천식','아토피피부염','골관절염','우울증']

# BE부분 운동관련
exercise=[
    'BE3_31',
    'BE5_1'   
] 
#건강검진
health_check = [
'HE_fst',
 'HE_HPdr',
 'HE_DMdr',
 'HE_mens',
 'HE_prg',
 'HE_HPfh1',
 'HE_HPfh2',
 'HE_HPfh3',
 'HE_HLfh1',
 'HE_HLfh2',
 'HE_HLfh3',
 'HE_IHDfh1',
 'HE_IHDfh2',
 'HE_IHDfh3',
 'HE_STRfh1',
 'HE_STRfh2',
 'HE_STRfh3',
 'HE_DMfh1',
 'HE_DMfh2',
 'HE_DMfh3',
 'HE_rPLS',
 'HE_sbp',
 'HE_dbp',
 'HE_ht',
 'HE_wt',
 'HE_wc',
 'HE_BMI',
 'HE_glu',
 'HE_HbA1c',
 'HE_chol',
 'HE_HDL_st2',
 'HE_TG',
 'HE_ast',
 'HE_alt',
 'HE_hepaB',
 'HE_HB',
 'HE_HCT',
 'HE_BUN',
 'HE_crea',
 'HE_WBC',
 'HE_RBC',
 'HE_Bplt',
 'HE_Uph',
 'HE_Unitr',
 'HE_Usg',
 'HE_Upro',
 'HE_Uglu',
 'HE_Uket',
 'HE_Ubil',
 'HE_Ubld',
 'HE_Uro',
 'HE_Ucrea'
]
 
low_nurition = ['N_PROT','N_FAT','N_FE','N_RETIN','N_B1','N_B2','N_NIAC','N_VITC']
low_nurition_name = ['단백질','지방','철','레티놀', '티아민','리보플라빈','나이아신','비타민C']
low_low_nurition = ['N_FE','N_B1','N_B2']
low_low_nurition_name = ['철','티아민','리보플라빈']


# 회귀분석

로지스틱 회귀분석

In [112]:
# 회귀분석 전처리

In [113]:
for i in range(len(disease)):
  health = health.replace({disease[i] : -1}, 0)
  # health[disease[i]] == health[disease[i]].apply(find)

## 고혈압

In [114]:
hb_mean_columns = [
    'age','비만','당뇨병','고콜레스테롤혈증','HE_sbp','HE_dbp','HE_wc','HE_BMI','총질병수','HE_HPdr'
    ,'HE_glu','HE_HbA1c','HE_BUN'
]

features = health[hb_mean_columns]
get_d = health['고혈압']

 

In [115]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_labels, test_labels = train_test_split(features, get_d)

In [116]:
print(train_features)
print(train_labels)

       age   비만  당뇨병  고콜레스테롤혈증  HE_sbp  HE_dbp  HE_wc     HE_BMI  총질병수  \
5626    80  0.0  0.0       0.0   147.0    74.0   87.5  24.347907     2   
24303   54  0.0  0.0       0.0   121.0    88.0   77.5  21.635439     1   
29161   36  0.0  0.0       1.0   101.0    67.0   76.7  19.969924     1   
9341    30  0.0  0.0       0.0   116.0    71.0   71.5  20.042891     1   
1649    47  0.0  0.0       1.0   109.0    70.0   82.8  23.523966     2   
...    ...  ...  ...       ...     ...     ...    ...        ...   ...   
29332   53  1.0  0.0       0.0   128.0    88.0   92.6  27.240273     1   
26332   66  0.0  1.0       0.0   146.0    59.0   75.7  20.210925     2   
20482   55  0.0  0.0       0.0   134.0    91.0   82.1  23.919574     1   
22139   63  1.0  0.0       0.0   115.0    86.0   88.0  30.041219     3   
18629   35  1.0  0.0       0.0   128.0    79.0   94.6  29.918605     1   

       HE_HPdr  HE_glu  HE_HbA1c  HE_BUN  
5626       0.0    92.0       4.9    15.0  
24303      0.0    89.0   

In [117]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

In [118]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(train_features, train_labels)

LogisticRegression()

In [119]:
print(model.score(train_features, train_labels))

0.8869802776842184


In [120]:
print(model.coef_)
# 'age','당뇨병','HE_sbp','HE_dbp','HE_wc','HE_BMI','총질병수'

[[ 0.58094167 -0.97698953 -0.48774038 -0.67139384  1.36943318  0.53570863
   0.28866637  0.07672467  2.84538265  0.71398208  0.13655143 -0.21222989
   0.17187548]]


In [121]:
alone_old_grand[hb_mean_columns].mean()

age          73.821184
비만            0.394281
당뇨병           0.305679
고콜레스테롤혈증      0.346355
HE_sbp      130.242851
HE_dbp       72.701571
HE_wc        85.262827
HE_BMI       24.275683
총질병수          2.683850
HE_HPdr      -0.072896
HE_glu      106.474426
HE_HbA1c      6.117479
HE_BUN       17.096657
dtype: float64

In [122]:
me  = np.array([alone_old_grand[hb_mean_columns].mean()]) #독거노인평균

In [123]:
me

array([[ 7.38211841e+01,  3.94281112e-01,  3.05678615e-01,
         3.46355215e-01,  1.30242851e+02,  7.27015707e+01,
         8.52628272e+01,  2.42756825e+01,  2.68385018e+00,
        -7.28956907e-02,  1.06474426e+02,  6.11747886e+00,
         1.70966573e+01]])

In [124]:
me = scaler.transform(me)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [125]:
print(model.predict(me))

[1.]


In [126]:
print(model.predict_proba(me))

#독거노인이 고혈압걸릴확률 84퍼센트

[[0.15662281 0.84337719]]


## 당뇨병

In [127]:
diabetes_mean_columns = [
    'age','고혈압','HE_wc','HE_glu','HE_HbA1c','HE_Uglu','총질병수'
]

features = alone_old_grand[diabetes_mean_columns]
get_d = alone_old_grand['당뇨병']

 

In [128]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_labels, test_labels = train_test_split(features, get_d)

In [129]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

In [130]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(train_features, train_labels)

LogisticRegression()

In [131]:
print(model.score(train_features, train_labels))

0.9269602577873255


In [132]:
print(model.coef_)
#  'age','고혈압','HE_wc','HE_glu','HE_HbA1c','HE_Uglu','총질병수'

[[ 0.083534   -0.28121799 -0.33478542  2.12697813  3.36045925  0.40039372
   1.20137545]]


In [133]:
me  = np.array([alone_old_grand[diabetes_mean_columns].mean()]) #독거노인평균

In [134]:
me

array([[ 73.82118405,   0.66089408,  85.26282723, 106.4744261 ,
          6.11747886,   0.12525171,   2.68385018]])

In [135]:
me = scaler.transform(me)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [136]:
print(model.predict(me))

[0.]


In [137]:
print(model.predict_proba(me))

[[0.74112162 0.25887838]]


In [138]:
#독거노인이 당뇨걸릴확률 26퍼센트

##고콜레스테롤혈증

In [139]:
hyperlipidemia_mean_columns = [
    'age','HE_chol','총질병수','고혈압'
]

features = health[hyperlipidemia_mean_columns]
get_d = health['고콜레스테롤혈증']

 

In [140]:
from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(features, get_d)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(train_features, train_labels)

print(model.score(train_features, train_labels))

print(model.coef_)
#  'HE_chol','총질병수'



0.8284121103252123
[[ 0.2368598   0.70226368  1.6773917  -0.4101391 ]]


In [141]:
me  = np.array([alone_old_grand[hyperlipidemia_mean_columns].mean()]) #독거노인평균

In [142]:
me = scaler.transform(me)
print(model.predict(me))
print(model.predict_proba(me))

# 독거노인 고콜레스테롤 걸릴확률 : 34퍼센트

[0.]
[[0.656537 0.343463]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


## 골관절염

In [143]:
osteoarthritis_mean_columns = [
    'age','뇌졸중','천식','아토피피부염','협심증또는심근경색증','우울증','총질병수'
]

# print(stroke_mean_columns)


features = health[osteoarthritis_mean_columns]
get_d = health['골관절염']

 



In [144]:
from sklearn.model_selection import train_test_split
train_features, test_features, train_labels, test_labels = train_test_split(features, get_d)

print(train_features)
print(train_labels)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
train_features = scaler.fit_transform(train_features)
test_features = scaler.transform(test_features)

from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(train_features, train_labels)

print(model.score(train_features, train_labels))

print(model.coef_)
#   'HE_chol','HE_wt','HE_wc','HE_TG','HE_HB'



       age  뇌졸중   천식  아토피피부염  협심증또는심근경색증  우울증  총질병수
8258    47  0.0  0.0     0.0         0.0  0.0     1
32231   39  0.0  0.0     0.0         0.0  0.0     0
7446    58  0.0  0.0     0.0         0.0  0.0     1
24937   60  0.0  0.0     0.0         0.0  0.0     0
35017   55  0.0  0.0     0.0         0.0  0.0     1
...    ...  ...  ...     ...         ...  ...   ...
25242   68  0.0  0.0     0.0         0.0  0.0     4
23098   34  0.0  0.0     0.0         0.0  0.0     1
9865    45  0.0  0.0     0.0         0.0  0.0     2
5179    68  0.0  0.0     0.0         0.0  0.0     2
5029    63  0.0  0.0     0.0         0.0  0.0     0

[26721 rows x 7 columns]
8258     0.0
32231    0.0
7446     0.0
24937    0.0
35017    0.0
        ... 
25242    0.0
23098    0.0
9865     0.0
5179     0.0
5029     0.0
Name: 골관절염, Length: 26721, dtype: float64
0.8726844055237454
[[ 0.9284879  -0.20311405 -0.06477156 -0.04074665 -0.20822068  0.00466743
   1.15083792]]


In [145]:
me  = np.array([alone_old_grand[osteoarthritis_mean_columns].mean()]) #독거노인평균
print(me)

[[ 7.38211841e+01 -1.08739428e-01 -1.04309303e-01 -1.57873540e-01
  -8.41723721e-02 -6.32299638e-02  2.68385018e+00]]


In [146]:
me = scaler.transform(me)
print(model.predict(me))
print(model.predict_proba(me))

# 독거노인 협심증또는 심근경색증 걸릴확률 : 44퍼센트

[0.]
[[0.55847523 0.44152477]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
